Correção View SearchBar - preto
analuramalho/PI_MarvelApp pull request #46
Opened 2021-02-02 00:13 UTC by giuliamachado03

Correção:

#4 - Plano de fundo preto na imagem

2021-02-02 01:23 UTC, giuliamachado03 commented
# 9 - Adicionar margem inferior no nome do personagem

2021-02-02 02:16 UTC, klossteles commented on marvelApp/app/src/main/res/layout/fragment_character_list_item.xml
> +            android:layout_marginTop="10dp"
Extrair dimensões.

2021-02-02 02:17 UTC, klossteles requested changes
Necessário extrair dimensões.

2021-02-02 02:17 UTC, klossteles commented on marvelApp/app/src/main/res/layout/fragment_comic_list_item.xml
> +            android:layout_marginTop="10dp"
Extrair dimensões

2021-02-02 02:17 UTC, klossteles commented on marvelApp/app/src/main/res/layout/fragment_creators_item_list.xml
>              android:layout_height="wrap_content"
Extrair dimensões

2021-02-02 02:17 UTC, klossteles commented on marvelApp/app/src/main/res/layout/fragment_series_list_item.xml
> +            android:layout_marginBottom="15dp"
Extrair dimensões

2021-02-04 02:02 UTC, klossteles approved these changes

2021-02-04 02:10 UTC, merged